# CMake generated Testfile for 
# Source directory: /Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test
# Build directory: /Users/voglab04/gudhi-devel/src/src/Coxeter_triangulation/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Coxeter_triangulation_permutahedral_representation_test "/Users/voglab04/gudhi-devel/src/src/Coxeter_triangulation/test/Coxeter_triangulation_permutahedral_representation_test" "--color_output" "--report_level=detailed")
set_tests_properties(Coxeter_triangulation_permutahedral_representation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;7;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;0;")
add_test(Coxeter_triangulation_freudenthal_triangulation_test "/Users/voglab04/gudhi-devel/src/src/Coxeter_triangulation/test/Coxeter_triangulation_freudenthal_triangulation_test" "--color_output" "--report_level=detailed")
set_tests_properties(Coxeter_triangulation_freudenthal_triangulation_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;10;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;0;")
add_test(Coxeter_triangulation_functions_test "/Users/voglab04/gudhi-devel/src/src/Coxeter_triangulation/test/Coxeter_triangulation_functions_test" "--color_output" "--report_level=detailed")
set_tests_properties(Coxeter_triangulation_functions_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;13;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;0;")
add_test(Coxeter_triangulation_random_orthogonal_matrix_function_test "/Users/voglab04/gudhi-devel/src/src/Coxeter_triangulation/test/Coxeter_triangulation_random_orthogonal_matrix_function_test" "--color_output" "--report_level=detailed")
set_tests_properties(Coxeter_triangulation_random_orthogonal_matrix_function_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;19;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;0;")
add_test(Coxeter_triangulation_oracle_test "/Users/voglab04/gudhi-devel/src/src/Coxeter_triangulation/test/Coxeter_triangulation_oracle_test" "--color_output" "--report_level=detailed")
set_tests_properties(Coxeter_triangulation_oracle_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;23;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;0;")
add_test(Coxeter_triangulation_manifold_tracing_test "/Users/voglab04/gudhi-devel/src/src/Coxeter_triangulation/test/Coxeter_triangulation_manifold_tracing_test" "--color_output" "--report_level=detailed")
set_tests_properties(Coxeter_triangulation_manifold_tracing_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;26;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;0;")
add_test(Coxeter_triangulation_cell_complex_test "/Users/voglab04/gudhi-devel/src/src/Coxeter_triangulation/test/Coxeter_triangulation_cell_complex_test" "--color_output" "--report_level=detailed")
set_tests_properties(Coxeter_triangulation_cell_complex_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;29;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Coxeter_triangulation/test/CMakeLists.txt;0;")
