# CMake generated Testfile for 
# Source directory: /Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes
# Build directory: /Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Persistence_representation_utilities_create_landscapes "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/create_landscapes" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../second.pers")
set_tests_properties(Persistence_representation_utilities_create_landscapes PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;10;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;3;add_persistence_representation_creation_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_landscapes_first "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/plot_landscapes" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../first.pers.land")
set_tests_properties(Persistence_representation_utilities_plot_landscapes_first PROPERTIES  DEPENDS "Persistence_representation_utilities_create_landscapes" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;21;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;5;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_landscapes_first_gnuplot "/opt/homebrew/bin/gnuplot" "-e" "load '/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../first.pers.land_GnuplotScript'")
set_tests_properties(Persistence_representation_utilities_plot_landscapes_first_gnuplot PROPERTIES  DEPENDS "Persistence_representation_utilities_plot_landscapes_first" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;28;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;5;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_average_landscapes "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/average_landscapes" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../first.pers.land" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../second.pers.land")
set_tests_properties(Persistence_representation_utilities_average_landscapes PROPERTIES  DEPENDS "Persistence_representation_utilities_create_landscapes" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;7;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_distance_of_landscapes "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/compute_distance_of_landscapes" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../first.pers.land" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../second.pers.land")
set_tests_properties(Persistence_representation_utilities_compute_distance_of_landscapes PROPERTIES  DEPENDS "Persistence_representation_utilities_create_landscapes" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;8;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_scalar_product_of_landscapes "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/compute_scalar_product_of_landscapes" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../first.pers.land" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes/../second.pers.land")
set_tests_properties(Persistence_representation_utilities_compute_scalar_product_of_landscapes PROPERTIES  DEPENDS "Persistence_representation_utilities_create_landscapes" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;9;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes/CMakeLists.txt;0;")
