# CMake generated Testfile for 
# Source directory: /Users/voglab04/gudhi-devel/src/Alpha_complex/utilities
# Build directory: /Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Alpha_complex_utilities_safe_alpha_complex_persistence "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_persistence" "/Users/voglab04/gudhi-devel/data/points/tore3D_300.off" "-p" "2" "-m" "0.45" "-o" "safe.pers")
set_tests_properties(Alpha_complex_utilities_safe_alpha_complex_persistence PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;11;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_fast_alpha_complex_persistence "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_persistence" "/Users/voglab04/gudhi-devel/data/points/tore3D_300.off" "-p" "2" "-m" "0.45" "-o" "fast.pers" "-f")
set_tests_properties(Alpha_complex_utilities_fast_alpha_complex_persistence PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;13;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_exact_alpha_complex_persistence "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_persistence" "/Users/voglab04/gudhi-devel/data/points/tore3D_300.off" "-p" "2" "-m" "0.45" "-o" "exact.pers" "-e")
set_tests_properties(Alpha_complex_utilities_exact_alpha_complex_persistence PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;15;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_diff_exact_alpha_complex "/usr/bin/diff" "exact.pers" "safe.pers")
set_tests_properties(Alpha_complex_utilities_diff_exact_alpha_complex PROPERTIES  DEPENDS "Alpha_complex_utilities_exact_alpha_complex_persistence;Alpha_complex_utilities_safe_alpha_complex_persistence" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;18;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_diff_fast_alpha_complex "/usr/bin/diff" "fast.pers" "safe.pers")
set_tests_properties(Alpha_complex_utilities_diff_fast_alpha_complex PROPERTIES  DEPENDS "Alpha_complex_utilities_fast_alpha_complex_persistence;Alpha_complex_utilities_safe_alpha_complex_persistence" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;23;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_alpha_complex_3d "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_3d_persistence" "/Users/voglab04/gudhi-devel/data/points/tore3D_300.off" "-p" "2" "-m" "0.45" "-o" "safe_3d.pers")
set_tests_properties(Alpha_complex_utilities_alpha_complex_3d PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;41;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_exact_alpha_complex_3d "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_3d_persistence" "/Users/voglab04/gudhi-devel/data/points/tore3D_300.off" "-p" "2" "-m" "0.45" "-o" "exact_3d.pers" "-e")
set_tests_properties(Alpha_complex_utilities_exact_alpha_complex_3d PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;45;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_fast_alpha_complex_3d "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_3d_persistence" "/Users/voglab04/gudhi-devel/data/points/tore3D_300.off" "-p" "2" "-m" "0.45" "-o" "fast_3d.pers" "-f")
set_tests_properties(Alpha_complex_utilities_fast_alpha_complex_3d PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;49;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_diff_exact_alpha_complex_3d "/usr/bin/diff" "exact_3d.pers" "safe_3d.pers")
set_tests_properties(Alpha_complex_utilities_diff_exact_alpha_complex_3d PROPERTIES  DEPENDS "Alpha_complex_utilities_exact_alpha_complex_3d;Alpha_complex_utilities_alpha_complex_3d" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;54;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_diff_fast_alpha_complex_3d "/usr/bin/diff" "fast_3d.pers" "safe_3d.pers")
set_tests_properties(Alpha_complex_utilities_diff_fast_alpha_complex_3d PROPERTIES  DEPENDS "Alpha_complex_utilities_fast_alpha_complex_3d;Alpha_complex_utilities_alpha_complex_3d" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;58;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_periodic_alpha_complex_3d_persistence "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_3d_persistence" "/Users/voglab04/gudhi-devel/data/points/grid_10_10_10_in_0_1.off" "-c" "/Users/voglab04/gudhi-devel/data/points/iso_cuboid_3_in_0_1.txt" "-p" "2" "-m" "0")
set_tests_properties(Alpha_complex_utilities_periodic_alpha_complex_3d_persistence PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;64;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_weighted_alpha_complex_3d "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_3d_persistence" "/Users/voglab04/gudhi-devel/data/points/grid_10_10_10_in_0_1.off" "-w" "/Users/voglab04/gudhi-devel/data/points/grid_10_10_10_in_0_1.weights" "-p" "2" "-m" "0")
set_tests_properties(Alpha_complex_utilities_weighted_alpha_complex_3d PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;69;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
add_test(Alpha_complex_utilities_weighted_periodic_alpha_complex_3d "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/utilities/alpha_complex_3d_persistence" "/Users/voglab04/gudhi-devel/data/points/grid_10_10_10_in_0_1.off" "-w" "/Users/voglab04/gudhi-devel/data/points/grid_10_10_10_in_0_1.weights" "-c" "/Users/voglab04/gudhi-devel/data/points/iso_cuboid_3_in_0_1.txt" "-p" "2" "-m" "0" "-e")
set_tests_properties(Alpha_complex_utilities_weighted_periodic_alpha_complex_3d PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;74;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/utilities/CMakeLists.txt;0;")
