# CMake generated Testfile for 
# Source directory: /Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps
# Build directory: /Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Persistence_representation_utilities_create_pssk "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/create_pssk" "10" "-1" "-1" "4" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../second.pers")
set_tests_properties(Persistence_representation_utilities_create_pssk PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;10;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;3;add_persistence_representation_creation_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_create_p_h_m_weighted_by_arctan_of_their_persistence "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/create_p_h_m_weighted_by_arctan_of_their_persistence" "10" "-1" "-1" "4" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../second.pers")
set_tests_properties(Persistence_representation_utilities_create_p_h_m_weighted_by_arctan_of_their_persistence PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;10;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;4;add_persistence_representation_creation_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_create_p_h_m_weighted_by_distance_from_diagonal "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/create_p_h_m_weighted_by_distance_from_diagonal" "10" "-1" "-1" "4" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../second.pers")
set_tests_properties(Persistence_representation_utilities_create_p_h_m_weighted_by_distance_from_diagonal PROPERTIES  DEPENDS "Persistence_representation_utilities_create_p_h_m_weighted_by_arctan_of_their_persistence" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;10;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;6;add_persistence_representation_creation_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_create_p_h_m_weighted_by_squared_diag_distance "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/create_p_h_m_weighted_by_squared_diag_distance" "10" "-1" "-1" "4" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../second.pers")
set_tests_properties(Persistence_representation_utilities_create_p_h_m_weighted_by_squared_diag_distance PROPERTIES  DEPENDS "Persistence_representation_utilities_create_p_h_m_weighted_by_distance_from_diagonal" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;10;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;11;add_persistence_representation_creation_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_create_persistence_heat_maps "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/create_persistence_heat_maps" "10" "0" "35" "10" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../second.pers")
set_tests_properties(Persistence_representation_utilities_create_persistence_heat_maps PROPERTIES  DEPENDS "Persistence_representation_utilities_create_p_h_m_weighted_by_squared_diag_distance" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;10;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;17;add_persistence_representation_creation_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_persistence_heat_map_first "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/plot_persistence_heat_map" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers.mps")
set_tests_properties(Persistence_representation_utilities_plot_persistence_heat_map_first PROPERTIES  DEPENDS "Persistence_representation_utilities_create_persistence_heat_maps" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;21;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;21;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_persistence_heat_map_first_gnuplot "/opt/homebrew/bin/gnuplot" "-e" "load '/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers.mps_GnuplotScript'")
set_tests_properties(Persistence_representation_utilities_plot_persistence_heat_map_first_gnuplot PROPERTIES  DEPENDS "Persistence_representation_utilities_plot_persistence_heat_map_first" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;28;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;21;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_average_persistence_heat_maps "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/average_persistence_heat_maps" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers.mps" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../second.pers.mps")
set_tests_properties(Persistence_representation_utilities_average_persistence_heat_maps PROPERTIES  DEPENDS "Persistence_representation_utilities_create_persistence_heat_maps" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;23;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_distance_of_persistence_heat_maps "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/compute_distance_of_persistence_heat_maps" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers.mps" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../second.pers.mps")
set_tests_properties(Persistence_representation_utilities_compute_distance_of_persistence_heat_maps PROPERTIES  DEPENDS "Persistence_representation_utilities_create_persistence_heat_maps" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;24;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_scalar_product_of_persistence_heat_maps "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/compute_scalar_product_of_persistence_heat_maps" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../first.pers.mps" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_heat_maps/../second.pers.mps")
set_tests_properties(Persistence_representation_utilities_compute_scalar_product_of_persistence_heat_maps PROPERTIES  DEPENDS "Persistence_representation_utilities_create_persistence_heat_maps" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;25;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_heat_maps/CMakeLists.txt;0;")
