# CMake generated Testfile for 
# Source directory: /Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals
# Build directory: /Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Persistence_representation_utilities_plot_histogram_of_intervals_lengths "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/plot_histogram_of_intervals_lengths" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../first.pers" "-1")
set_tests_properties(Persistence_representation_utilities_plot_histogram_of_intervals_lengths PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;6;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_persistence_intervals_first "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/plot_persistence_intervals" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../first.pers")
set_tests_properties(Persistence_representation_utilities_plot_persistence_intervals_first PROPERTIES  DEPENDS "Persistence_representation_utilities_plot_histogram_of_intervals_lengths" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;21;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;11;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_persistence_intervals_first_gnuplot "/opt/homebrew/bin/gnuplot" "-e" "load '/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../first.pers_GnuplotScript'")
set_tests_properties(Persistence_representation_utilities_plot_persistence_intervals_first_gnuplot PROPERTIES  DEPENDS "Persistence_representation_utilities_plot_persistence_intervals_first" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;28;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;11;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_persistence_Betti_numbers_first "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/plot_persistence_Betti_numbers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../first.pers")
set_tests_properties(Persistence_representation_utilities_plot_persistence_Betti_numbers_first PROPERTIES  DEPENDS "Persistence_representation_utilities_plot_histogram_of_intervals_lengths" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;21;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;12;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_persistence_Betti_numbers_first_gnuplot "/opt/homebrew/bin/gnuplot" "-e" "load '/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../first.pers_GnuplotScript'")
set_tests_properties(Persistence_representation_utilities_plot_persistence_Betti_numbers_first_gnuplot PROPERTIES  DEPENDS "Persistence_representation_utilities_plot_persistence_Betti_numbers_first" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;28;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;12;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_birth_death_range_in_persistence_diagram "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/compute_birth_death_range_in_persistence_diagram" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../second.pers")
set_tests_properties(Persistence_representation_utilities_compute_birth_death_range_in_persistence_diagram PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;10;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;14;add_persistence_representation_creation_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_number_of_dominant_intervals "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/compute_number_of_dominant_intervals" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../first.pers" "-1" "2")
set_tests_properties(Persistence_representation_utilities_compute_number_of_dominant_intervals PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;17;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_bottleneck_distance "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/compute_bottleneck_distance" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_intervals/../second.pers")
set_tests_properties(Persistence_representation_utilities_compute_bottleneck_distance PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;29;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_intervals/CMakeLists.txt;0;")
