# CMake generated Testfile for 
# Source directory: /Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid
# Build directory: /Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Persistence_representation_utilities_create_landscapes_on_grid "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/create_landscapes_on_grid" "100" "0" "35" "-1" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../first.pers" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../second.pers")
set_tests_properties(Persistence_representation_utilities_create_landscapes_on_grid PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;10;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;4;add_persistence_representation_creation_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_landscapes_on_grid_first "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/plot_landscapes_on_grid" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../first.pers.g_land")
set_tests_properties(Persistence_representation_utilities_plot_landscapes_on_grid_first PROPERTIES  DEPENDS "Persistence_representation_utilities_create_landscapes_on_grid" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;21;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;6;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_plot_landscapes_on_grid_first_gnuplot "/opt/homebrew/bin/gnuplot" "-e" "load '/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../first.pers.g_land_GnuplotScript'")
set_tests_properties(Persistence_representation_utilities_plot_landscapes_on_grid_first_gnuplot PROPERTIES  DEPENDS "Persistence_representation_utilities_plot_landscapes_on_grid_first" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;28;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;6;add_persistence_representation_plot_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_average_landscapes_on_grid "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/average_landscapes_on_grid" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../first.pers.g_land" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../second.pers.g_land")
set_tests_properties(Persistence_representation_utilities_average_landscapes_on_grid PROPERTIES  DEPENDS "Persistence_representation_utilities_create_landscapes_on_grid" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;8;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_distance_of_landscapes_on_grid "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/compute_distance_of_landscapes_on_grid" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../first.pers.g_land" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../second.pers.g_land")
set_tests_properties(Persistence_representation_utilities_compute_distance_of_landscapes_on_grid PROPERTIES  DEPENDS "Persistence_representation_utilities_create_landscapes_on_grid" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;9;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;0;")
add_test(Persistence_representation_utilities_compute_scalar_product_of_landscapes_on_grid "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/compute_scalar_product_of_landscapes_on_grid" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../first.pers.g_land" "/Users/voglab04/gudhi-devel/src/src/Persistence_representations/utilities/persistence_landscapes_on_grid/../second.pers.g_land")
set_tests_properties(Persistence_representation_utilities_compute_scalar_product_of_landscapes_on_grid PROPERTIES  DEPENDS "Persistence_representation_utilities_create_landscapes_on_grid" _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/CMakeLists.txt;51;add_test;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;10;add_persistence_representation_function_utility;/Users/voglab04/gudhi-devel/src/Persistence_representations/utilities/persistence_landscapes_on_grid/CMakeLists.txt;0;")
