# CMake generated Testfile for 
# Source directory: /Users/voglab04/gudhi-devel/src/Alpha_complex/test
# Build directory: /Users/voglab04/gudhi-devel/src/src/Alpha_complex/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Alpha_complex_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Alpha_complex_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Alpha_complex_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;30;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Alpha_complex_dim3_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Alpha_complex_dim3_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Alpha_complex_dim3_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;31;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Delaunay_complex_Epeck_dynamic_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Delaunay_complex_Epeck_dynamic_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Delaunay_complex_Epeck_dynamic_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;32;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Delaunay_complex_Epeck_static_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Delaunay_complex_Epeck_static_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Delaunay_complex_Epeck_static_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;33;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Delaunay_complex_Epick_dynamic_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Delaunay_complex_Epick_dynamic_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Delaunay_complex_Epick_dynamic_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;34;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Delaunay_complex_Epick_static_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Delaunay_complex_Epick_static_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Delaunay_complex_Epick_static_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;35;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Alpha_complex_3d_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Alpha_complex_3d_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Alpha_complex_3d_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;56;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Weighted_alpha_complex_3d_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Weighted_alpha_complex_3d_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Weighted_alpha_complex_3d_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;57;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Periodic_alpha_complex_3d_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Periodic_alpha_complex_3d_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Periodic_alpha_complex_3d_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;58;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Weighted_periodic_alpha_complex_3d_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Weighted_periodic_alpha_complex_3d_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Weighted_periodic_alpha_complex_3d_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;59;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Alpha_kernel_d_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Alpha_kernel_d_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Alpha_kernel_d_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;69;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Weighted_alpha_complex_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Weighted_alpha_complex_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Weighted_alpha_complex_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;76;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Weighted_alpha_complex_non_visible_points_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Weighted_alpha_complex_non_visible_points_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Weighted_alpha_complex_non_visible_points_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;83;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
add_test(Zero_weighted_alpha_complex_test_unit "/Users/voglab04/gudhi-devel/src/src/Alpha_complex/test/Zero_weighted_alpha_complex_test_unit" "--color_output" "--report_level=detailed")
set_tests_properties(Zero_weighted_alpha_complex_test_unit PROPERTIES  _BACKTRACE_TRIPLES "/Users/voglab04/gudhi-devel/src/cmake/modules/GUDHI_boost_test.cmake;26;add_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;90;gudhi_add_boost_test;/Users/voglab04/gudhi-devel/src/Alpha_complex/test/CMakeLists.txt;0;")
